version: '3.7'

services:
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  web:
    build: .
    command: hanami server --host=0.0.0.0
    ports:
      - 2300:2300
    volumes:
      - $PWD:/app
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:10.4-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    stdin_open: true
    tty: true

volumes:
    db_data:
    portainer_data: